from .PrimeiraEtapa import PrimeiraEtapa
from .SegundaEtapa import SegundaEtapa
from .TerceiraEtapaLivre import TerceiraEtapaLivre
from .TerceiraEtapaComObstaculos import TerceiraEtapaComObstaculos
from .QuartaEtapaObservavel import QuartaEtapaObservavel